spring.application.name=traffic-enforcement

spring.datasource.url=${DB_URL_PRIVATE}
#spring.datasource.url=${DB_URL_PUBLIC}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.web.error.include-message=always

paystack.secret-key=sk_test_78a1c561dbcb43015987e3ca5802ec665784a08d
paystack.base-url=https://api.paystack.co
